### ISSUE TITLE
Does x-lvc supports federation policies. 

### ISSUE THREAD

**Issue by naveene84** [rabbitmq/rabbitmq-lvc-plugin#15]
Hi,

My scenario is, I have two clusters C1 and C2 with 3 rabbitmq nodes on each cluster. 'RMQLvc1' exchange of type x-lvc is created in both clusters.  I wanted to consume messages publised to C1  from C2 and vise versa.
To achieve this, i have applied exchange federation policy to RMQLvc1 but not working.
 Please confirm, does x-lvc supports federation policies.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Exchange federation generally works for any exchange type. However, since this particular exchange re-publishes messages when a new binding is created, it will publish duplicates when federated as bindings are propagated by the federation plugin.
